[package]
name = "hellorust"
version = "0.1.0"
edition = "2021" 

[dependencies]
warp = "0.3"
tokio = { version="1" , features = ["full"] }
tracing-subscriber = "0.3.9" 
pretty_env_logger = "0.4"
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"