[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021" 

[dependencies]
warp = "0.3"
tokio = { version="1" , features = ["full"] }
tracing-subscriber = "0.3.9" 
pretty_env_logger = "0.4"